### ISSUE TITLE
MCP2542FD on HuvudTiny2

### ISSUE THREAD

**Issue by madhunm** [bondus/KlipperToolboard#10]
Do you think replacing the SN65HVD230 with MCP2542FD  makes sense?

You have the CanHatFD; adding the MCP2542FD will extend the capability...

Also, what do you think about adding a rotary position encoder onto the back of the PCB? that way you could have a closed loop stepper driver.

**Comment by bondus** [comment]
The STM32 used can not do CAN-FD, so an FD capable transceiver is not needed. 
The old CAN2.0B is good enough, at 1mbps you can easily run 10 Huvud boards.

I did think about a rotation sensor, but imo it's not a good idea. It's easier to get a bigger stepper.
