### ISSUE TITLE
Switching PSU on CanHatFD

### ISSUE THREAD

**Issue by madhunm** [bondus/KlipperToolboard#11]
If we could integrate a switching power supply to drop the V-In to 5v, we could avoid powering the Raspberry Pi over USB. I have not read much into the backpowering via the 5V pin; but, this is a feature you could consider.

Meanwell has a ready to use module: MDS15B-05 (18 ~ 36V in, 5V @ 3A out) Datasheet link: https://www.meanwell.com/webapp/product/search.aspx?prod=MDS15

They have a larger version as well: https://www.meanwell.com/webapp/product/search.aspx?prod=MDS20

I know they are on the larger side; but, they are usually fit and forget. No need to adjust the output voltage

**Comment by bondus** [comment]
It actually has got 4 pins for an external DCDC converter, I have tested it with some cheap ali converter. There is a back-powering protection diode, a mosfet solution would avoid the voltage drop over the diode. It's currently not a good solution.

The board works but it's not being further developed at the moment. It's quite tricky to get the linux kernel driver working.

Those MDS parts are large but more importantly very expensive, not really viable for a product like this.

Thanks for the suggestions
