### ISSUE TITLE
Endstop inputs

### ISSUE THREAD

**Issue by shavrin777** [bondus/KlipperToolboard#12]
Is it possible to add solder jumpers on the endstop inputs to disable pull-up resistors and RC filters so that these pins can be used as normal GPIOs? For example this can be used to connect servos or BLTouch.
![image](https://user-images.githubusercontent.com/37345777/114606430-eb869480-9ca3-11eb-9930-2d52e58559f6.png)

**Comment by bondus** [comment]
You can use the debug connector pins (SWDIN/SWDCLK and in some cases BOOT1) as GPIOs, they only have pull down resistors. There are two small pads on the back as well connected to PB10/PB11. 
Servos and BLTouch requires 5V to run, so you would need a separate DCDC to supply them.
