### ISSUE TITLE
Pins for the accelerometer? 

### ISSUE THREAD

**Issue by blairq** [bondus/KlipperToolboard#17]
I could not see pins for the accelerometer. 

Gnd, 3.3v , sclk miso and mosi?

**Comment by bondus** [comment]
v0.5 was not designed specifically to have pins for it. But you can hook one up, there are some pads on the bottom (PB10, PB11) and you can use the pins on the debug connectors. I have not tested it myself, but I have seen others do it.

V0.6 will have an accelerometer on board, so there are no pins for it.
