### ISSUE TITLE
ISOTP or ISOBus (J1939) for CAN protocol

### ISSUE THREAD

**Issue by olerem** [bondus/KlipperToolboard#19]
Hi, I was reading the Klipper CAN code and noticed that it is not using any protocols to send anything more then 8 bytes. This is not error proof especially for the "Waveshare Raspberry Pi CAN hat", the packets can be lost or go out of order.
I mainlined J1939 support to the Linux kernel, in case you are interested to implement it for Klipper - ping me, i'll try to help you.

**Comment by bondus** [comment]
CAN adapters not adhering to the standard is out of scope for this projets
