### ISSUE TITLE
JLCSMT_Sample_BOM1

### ISSUE THREAD

**Issue by Tiefschneegiftler** [bondus/KlipperToolboard#2]
LCSC Part C21190, the UNIROYAL 1k resistor is in there twice once in line 17 once in 18, with Designators R4 and R6 respectively, shouldn't they go into one line?
I think you have the description with a capital K in the one and the non cap k in the other so the automated BOM put it into two lines.

![image](https://user-images.githubusercontent.com/2293625/82200217-05d2b980-98ff-11ea-9421-d2398bbbf811.png)

**Comment by bondus** [comment]
You are right. But that BOM is very obsolete. The git was just now updated to the recent version.
