### ISSUE TITLE
Question: running this on a 12v system

### ISSUE THREAD

**Issue by varazir** [bondus/KlipperToolboard#24]
Hello, 

I like this idea and been looking for a solution for my Wanhao i3 v2.1. 
Found this when I watched eddietheengineers video. He mentioned that he had issue with 12v system. 
Could you add some type of heat sink to the board to alleviate the heat? 

I have moded my printer with a BLTouth probe and dual 12v blowers for part cooling. 

TIA 
Daniel

**Comment by bondus** [comment]
It will work perfectly fine with a standard 40-50W hot end heater at 12V
I do not recommend running it with a heater over 5A (60W at 12V)
