### ISSUE TITLE
POS files for v0.62 not correct

### ISSUE THREAD

**Issue by rtho782** [bondus/KlipperToolboard#45]
There seem to be some issues with the JLCPCB pos files for 0.62:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/25555587/192783673-bcf92f14-2129-4f9c-8166-ac34dfe4bd97.png">

Some components in the wrong places, and some rotated incorrectly, Cap upside down etc

I think I can correct most of it myself but I'm terrified of getting it all wrong!!

**Comment by bondus** [comment]
The files for JLCPBC were not updated, I forgot them. 
The rotations for JLC are always wrong and have to be fixed manually in their tool.

**Comment by bondus** [comment]
Fixed
