### ISSUE TITLE
Accelerometer?

### ISSUE THREAD

**Issue by Taudris** [bondus/KlipperToolboard#8]
Klipper semi-recently added support for using an accelerometer to help calibrate the input shaper. It would be awesome to have one built into this board (space and CAN bus bandwidth permitting).

**Comment by bondus** [comment]
Version 2, which is being developed, will have an integrated accelerator. Have a look at HuvudTiny2. 
We have tested wiring in an accelerometer to Huvud 0.50, it works fine.

**Comment by brotherdust** [comment]
@bondus 
> Have a look at HuvudTiny2.

Can you please provide a link to the HuvudTiny2? Interested in seeing how development is coming.
